version: 2.1

orbs:
  gradle: circleci/gradle@2.1.0

executors:
  java8:
    docker:
      - image: cimg/openjdk:8.0

jobs:
  jar:
    executor: java8
    steps:
      - run:
          name: build JAR
          command: gradle jar
      - store_artifacts:
          path: build/libs/

workflows:
  build:
    jobs:
      - gradle/test:
          executor: java8
      - jar:
          requires:
            - gradle/test
